apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: python-app-destination
spec:
  host: python-app-service
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: python-app-gateway
spec:
  selector:
    istio: ingressgateway # use Istio's default ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: python-app-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - python-app-gateway
  http:
  - route:
    - destination:
        host: python-app-service
        subset: stable
      weight: 90
    - destination:
        host: python-app-service
        subset: canary
      weight: 10